/// <reference types="cypress" />

context('Strength analyser End to End test',()=>{
    it('Should test the whole Password Strength Analyser page and conduct an End to End test',()=>{
        cy.viewport(1920,1080)
        cy.visit('/analyser')
        //Page rendering tests
        cy.get('.navbar').should('be.visible')
        cy.get('.Home_analyser__UZXIM').should('be.visible')
        cy.findByRole('heading', {  name: /robust password strength analyser/i})
        cy.get('.my-5').should('contain.text','Robust Password strength analyser')
        cy.findByRole('heading', {  name: /analyse the strength of your password efficiently and be rest assured\-/i})
        cy.get('h5').should('contain.text','Analyse the strength of your password efficiently and be rest assured')
        cy.get('h5 > .mr-2').realHover().should('be.visible')
        cy.get('.form-control').should('be.enabled').should('not.have.value')
        cy.get('.progress-bar').should('not.be.visible')
        cy.get('h3.text-center').should('contain.text','Very Weak, easily crackable')
        //Testing functionality
        cy.get('.form-control').type('Password')
        cy.get('h3.text-center').should('have.css','color','rgb(0, 0, 0)')
        cy.get('.progress-bar').should('not.be.visible')
        cy.get('h3.text-center').should('contain.text','Very Weak, easily crackable')
        cy.get('.form-control').clear().type('Password123')
        cy.get('h3.text-center').should('have.css','color','rgb(234, 17, 17)')
        cy.get('.progress-bar').should('be.visible')
        cy.get('h3.text-center').should('contain.text','Weak-ish still')
        cy.get('.form-control').clear().type('Skljmn@')
        cy.get('h3.text-center').should('have.css','color','rgb(255, 242, 0)')
        cy.get('.progress-bar').should('be.visible')
        cy.get('h3.text-center').should('contain.text','Its Okay-ish')
        cy.get('.form-control').clear().type('Skljmn@12')
        cy.get('h3.text-center').should('have.css','color','rgb(102, 255, 0)')
        cy.get('.progress-bar').should('be.visible')
        cy.get('h3.text-center').should('contain.text','Better now...')
        cy.get('.form-control').clear().type('Skljmn@12@as')
        cy.get('h3.text-center').should('have.css','color','rgb(0, 255, 94)')
        cy.get('.progress-bar').should('be.visible')
        cy.get('h3.text-center').should('contain.text','Perfectly Strong & Complex!')
    })
})